version : "3"
services: 
  webproject:
    build: .
    ports: 
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/myDatabase
    depends_on:
      - mongo
  mongo:
    image: mongo
